### ISSUE TITLE
Quantitative analysis: merging the data with meta-data from brigades

### ISSUE THREAD

**Issue by jkropko** [codeforamerica/brigade-playbook#146]
### Overview
We need a have a total dataframe encompassing all data from priority ranking sheet, meet up data sheet, and brigade size & length sheet, so we can correlate responses with other features such as size of the brigade, activity level, and other things we can get from scraping Meetup, Github, or from C4A's data if they are willing to share.

### Dependencies
Knowledge of the tidyverse

### Action Items

- [x] Find as many brigade-level datasets as possible
  - [x] Priority ranking sheet
  - [x] Meet up data sheet 
  - [x] Brigade size & length sheets
- [x] Merge using dplyr with the interview response data
- [x] Create two data set 
  - [x] 1. With each ranking per row, questions in one column
  - [x] 2. with each interview per row, each question per column

### Resources/Instructions
  - [Priority ranking sheet](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=825325863)
  - [Meet up data sheet](https://docs.google.com/spreadsheets/d/10uZjjrXpZH-y6wZBHZvhKgWNUBj7Xvyh9yoiqL4F_9I/edit#gid=1930568343) 
  - [Brigade size & length sheets](https://docs.google.com/spreadsheets/d/10uZjjrXpZH-y6wZBHZvhKgWNUBj7Xvyh9yoiqL4F_9I/edit#gid=1930219941)

**Comment by tan-zhou** [comment]
I merged brigade size and leadership length with the total data, and calculate the quantiles

**Comment by tan-zhou** [comment]
Updated the action items to reflect the change in priority.

**Comment by tan-zhou** [comment]
add MSA data into the total data set

**Comment by tan-zhou** [comment]
Add preparedness values once GRM is finished

**Comment by thadk** [comment]
Hi @tan-zhou , I added the MSA data that I had previously generated for late 2020 brigades to the Tracking spreadsheet as the "MSAData" sheet. Please ignore all the columns data with "lookup_ignore" in the column name: https://docs.google.com/spreadsheets/d/10uZjjrXpZH-y6wZBHZvhKgWNUBj7Xvyh9yoiqL4F_9I/edit#gid=1158009600

**Comment by tan-zhou** [comment]
Blocker: The section of code that loads data from Google sheets is highly dependent on the formatting of the original sheet. If changes happen in the original sheet (sheet order, new column added), the code couldn't load data as desired.

**Comment by tan-zhou** [comment]
> Blocker: The section of code that loads data from Google sheets is highly dependent on the formatting of the original sheet. If changes happen in the original sheet (sheet order, new column added), the code couldn't load data as desired.

To solve this, refer to data sheet by name instead of order
