### ISSUE TITLE
Report work plan

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [codeforamerica/brigade-playbook#241]
### Overview
We need notes about our workplan in one place.

### Action Items
- [ ] Bonnie And Mary are reviewing the P&Ps
- [ ] Aleiya and Mary will go over Bonnies P&Ps and write review
- [ ] Sort p&p sheet by category, identifying which is closest to done and knocking it out
- [ ] review what p&ps 1-3 exist for this catagory and review them
- [ ] start drafting them into the report to see how they fit.

### Resources/Instructions
[P&Ps](https://docs.google.com/spreadsheets/d/1ZyeIDeHnzwjnkfYuhzeUZQo5tYXpbdnF-HKqN8cZy_A/edit#gid=0)
