### ISSUE TITLE
BOP: ALL Team meeting agenda

### ISSUE THREAD

**Issue by ExperimentsInHonesty** [codeforamerica/brigade-playbook#276]
### Overview
This issue tracks the agenda for our weekly meetings

#### Issue Template
```
## [Date ]  Meeting Agenda

### Prework to prep for meeting
- [ ] #  

### Roll call
- [ ] Esther
- [ ] ~Ksenia~
- [ ] Bonnie
- [ ] Sanju
- [ ] Aleiya
- [ ] Ethan

       
### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/Ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items
```

### Links to other agenda issues for your team 
(so that you can easily post on their agendas items that come up at yours)

### Previous Meetings (link to each comment with the date)

**Comment by ExperimentsInHonesty** [comment]
## 2024-02-12 Meeting Agenda

### Prework to prep for meeting
- [ ] #  

### Roll call
- [ ] Esther
- [ ] ~Ksenia~
- [ ] Bonnie
- [ ] Sanju
- [ ] Aleiya
- [ ] Ethan

       
### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/Ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] 
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ExperimentsInHonesty** [comment]
##20234-02-19 Meeting Agenda

### Prework to prep for meeting
- [ ] #  

### Roll call
- [ ] Esther
- [ ] ~Ksenia~
- [ ] Bonnie
- [ ] Sanju
- [ ] Aleiya
- [ ] Ethan

       
### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/Ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] If we don't get someone from CoP responding to our post #277, add Sanju to the calendar invite for onboarding
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by Estherchuks** [comment]
##   [2024-04-08] Meeting Agenda

### Prework to prep for meeting
- [ ] #  

### Roll call
- [ ] Esther
- [ ] ~Ksenia~
- [ ] Bonnie
- [ ] Sanju
- [ ] Aleiya
- [ ] Ethan

       
### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/Ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Ask Liz about this #261 
- [ ] [Figma](https://www.figma.com/file/XEr9WwIWKCVLaUZh5VQhXw/BOP-Design?type=design&node-id=5725%3A51&mode=design&t=TZL3nW8ILGcxtv2m-1)
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

### Task Items

**Comment by ag2463** [comment]
##   [2024-05-13] Meeting Agenda

### Prework to prep for meeting
- [ ] #  

### Roll call
- [ ] Esther
- [ ] ~Ksenia~
- [ ] Bonnie
- [X] Sanju
- [X] Aleiya
- [ ] Ethan

       
### Recurring items: Happens on the ________ meeting
 - [ ] review any issues that are in the [new issue approval column]
 - [ ] Accountability and Support Check.
    - [ ] Review assignments for each Team member
       - [ ] [Esther](https://github.com/hackforla/BOP/issues/assigned/Estherchuks)
       - [ ] ~[Ksenia](https://github.com/hackforla/BOP/issues/assigned/ksenia)~
       - [ ] [Bonnie](https://github.com/hackforla/BOP/issues/assigned/ExperimentsInHonesty)
       - [ ] [Sanju](https://github.com/hackforla/BOP/issues/assigned/sanjumv)
       - [ ] [Aleiya](https://github.com/hackforla/BOP/issues/assigned/Ag2463)
- [ ] finish adding labels to the issue that are still missing them (see audit links above)
- [ ] review issues with [epic label] and define how to break down further
- [ ] Review to see if there are any members to Onboard or Offboard 
      - [ ]  #

### New Items
- [ ] Ask Liz about this #261 
- [ ] [Figma](https://www.figma.com/file/XEr9WwIWKCVLaUZh5VQhXw/BOP-Design?type=design&node-id=5725%3A51&mode=design&t=TZL3nW8ILGcxtv2m-1)
- [ ] Carry over Items to next meeting that don't get addressed

### FYIs
-

### Notes from Meeting

- What is Practice Area? How are we defining this?
- Can we rename Source to 'created by'?
- Can we remove Primary column?
- Type can this be text instead of a symbol?
- Can we combine Part# and Primary into 1 column?
- Maybe have a Preview button (or Quick View button) at the end of the row to make screen less busy
- Submitted date?

### Task Items

**Comment by Rabia2219** [comment]
- https://github.com/civictechindex/BOP/issues/290
