### ISSUE TITLE
Setup Milestones and Initial Issues

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#3]
### Overview
We need to create milestones and associated issues to manage progress and create visibility against the project deliverables.

### Action Items

- [x] Program manager and Product Manager
   - [x]  Review milestones from Civic Opportunities Project and determine those applicable to BOP project.
- [x] Product Manager
    - [x] Create milestones
    - [x] Review and identify which issues are appropriate 
    - [x] Create the issues

### Resources/Instructions
[BOP Project Initial Issues ](https://docs.google.com/spreadsheets/d/1uSyfabe9njnvXs-JwXc8XWzqI4okhz0oa0m-ZE7OlIU/edit?ts=5f3c014aurl)

**Comment by ExperimentsInHonesty** [comment]
Here are the milestones and their related issues https://github.com/codeforamerica/brigade-playbook/milestones
