### ISSUE TITLE
CfA Issue Tracker 

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#30]
### Overview
Drive engagement from CfA by providing a matrix of responsibilities aligned to milestones and related issues for CfA input.  

### Action Items
- [x] Create matrix identifying milestones, issues, and assigning CfA responsibilities (based on MOCHA template)
- [x] Team to review matrix
- [x] Send matrix to Will for review 

### Resources/Instructions
[MOCHA Definition](https://www.managementcenter.org/resources/assigning-responsibilities/v)

**Comment by MasSamH** [comment]
@ExperimentsInHonesty Feels like we can close this one off now as we have the OKRs/WBS document. Thanks Sam

**Comment by MasSamH** [comment]
Replaced by [OKRs/WBS doc](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/edit?pli=1#gid=30376616)
