### ISSUE TITLE
Mixed methods to qualitative insights from research

### ISSUE THREAD

**Issue by MasSamH** [codeforamerica/brigade-playbook#48]
### Overview
We will enrich and validate research findings with any qualitative research that emerges from quant based answers (1-5 scored questions)  

### Action Items

- [x] Otter AI sign up 
- [x] Work flow
   - [x] Otter AI create transcript from voice recordings 
   - [x] Create second google form template to capture those additional transcribed findings / import answers into
   - [x] Transcription puts into buckets of what was said where
   - [x]  Validate the transcript template after a few interviews
   - [x] Field about who they are - use UXR number + notes field
   - [x] Transcription testing
        - [x] Manual setup of spreadsheet with defined fields per comment
        - [x] Scripted Output from Transcriptions (Python)  [details to be found in #49]
        - [x] Testing Procedure UXR [details to be found in #59] 
- [x] Test methodology between Project Team / Jonathan to test [details to be found in #59] 
- [x] Test one UXR manually with pilot [details to be found in #59] 
- [x] Rollout training to wider UXR group [details to be found in #59] 

Notes:
- People who signed up to do UXR research is a role
- People signing up for transcription is a different role
- We want to have a validation step, therefore interviewer should not be the transcriber

### Resources/Instructions
[Transcription Clean Up Template](https://docs.google.com/spreadsheets/d/1yVFOMqLves5vdHonhkyFSyZ0W5fnioEEBIYxGUSrRoI/edit#gid=0)
[Transcription Sheet Template](https://docs.google.com/spreadsheets/d/1SDdReZoN20M_uZ5CaN9y-F4mwqZ5pVkIPsA9AlCtjYs/edit#gid=1976949881)
[Research Analysis Plan](https://docs.google.com/document/d/10Z90J2TPnoVy3cG96zawP4rw1eeyrdlahPYgHkbn3Pg/edit#heading=h.er10l8530r5b)

**Comment by MasSamH** [comment]
**Transcription Clean-Up**
Going to have 1 sheet per interview 
Vertical not horizontal spreadsheet

**Manual Spreadsheet - Thad** @thadk 
Field allocations:
First column field name on left
Second column Existing text (form submission) 
Third column exactly what OtterAI says (taken from audio) 
Fourth column actual clean input 
Fifth column is 'notes'

**Scripted Output from Transcriptions - Jonathan** 
Generate script (Python) that wrangles which text belongs to which field in the survey - based on 12 interviews
Python script will download results from google form all transcripts from OtterAI
- Match which text matches which field in the survey 
- Output goes into one spreadsheet

**Comment by thadk** [comment]
I created a sheet in the Templates folder that can get us started on this.

Procedure for use:
Please do not share it as-is: it has full access to our interviewees results. 
Pick which row of the main results you want in the first orange part of the second sheet. (I didn’t come up with any fancy ID scheme: maybe something like the one we made for audio upload: 003_codeforcharlottesville_2020-10-22_Jonathan-Kropko, but there are a few more steps to do this)
I have re-ordered the fields only in the first sheet/tab.
Next select-all and copy and paste both the values (this way you don’t get the formulas) and the format from the first tab of this document into a totally new spreadsheet in a transcriptions folder. Naming scheme maybe like the proposed ID or OtterAI title?
In the new spreadsheet, I recommend freezing the first header row in the View->Freeze->1 row.
Share the new spreadsheet with the transcriber and make sure they have access to the corresponding otter.ai.

**Comment by MasSamH** [comment]
[Transcription Template](https://docs.google.com/spreadsheets/d/1SDdReZoN20M_uZ5CaN9y-F4mwqZ5pVkIPsA9AlCtjYs/edit#gid=1976949881)

**Comment by ExperimentsInHonesty** [comment]
@MarianneAnthonette will add columns to the UXR schedule spreadsheet with "Recording Uploaded (TRUE)" and "Transcription Done By (Persons name-wip/ persons name)"

**Comment by ExperimentsInHonesty** [comment]
We have created a folder called [Transcription Storage](https://drive.google.com/drive/u/0/folders/1Nrd_QaBMdY2oW5UIhGDBO6tLKCiM0f4o) where we are storing:
@MarianneAnthonette @thadk will decide what is going into the folder and organize accordingly so that it is easy for UXRs who are going to do the work of matching up the words with the answers into the individual spreadsheet templates.

**Comment by ExperimentsInHonesty** [comment]
@MarianneAnthonette will get started.

**Comment by ExperimentsInHonesty** [comment]
@thadk will move rows on template to match the interview question order.

**Comment by thadk** [comment]
Mari's notes on Transcription procedure for others to follow

- Copied the sheet from template to new spreadsheet. Deleted the current values (needs formula), then recopied the values into the new spreadsheet.
--
- Copied audio name. Do we want the name scheme to include UXR name at all?
- Good to have: A document that outlines Interview Transcription Procedure in the Transcription Storage folder. Has UXR Schedule link.
- Good to have: Spreadsheet should have specific link to Otter.ai audio for the transcriber's reference (keeps every asset transcriber needs together)
- Good to have: Exported text(?) How are we handling the Otter.ai exact text for each sheet (follow-up with Jon)
- Good to do: Tag people on Otter.ai before hand
- Make new sheet in UXR Schedule or a separate sheet to keep track of transcriptions (maybe move Interview Response List Sheet?)
- First pass (Otter.ai bucketing) took ~ an hour. Making the adjustments took a bit less than an hour
- Doesn't seem feasible that we can automate the bucketing because of how the interviews are conducted. It'll bring about confusion.
- Didn't use the Notes column. Unless we want the transcribers to do the first step of bucketing (But I feel like that would be too much to ask/this step could be essential for core team members to verify what is captured.
- Need for verifying the rankings before even doing quant analysis
- Definitely should start on creating a research analysis plan.
- Adding things to the assets sheet: What would be the absolute minimum needed so that it can make it on the sheet?

**Comment by ExperimentsInHonesty** [comment]
@MarianneAnthonette will go back to the spreadsheets and delete the row 158 artifact

**Comment by ExperimentsInHonesty** [comment]
Notes filed could be used to identify problems with the audio in case we need to follow up on what they said.

**Comment by ExperimentsInHonesty** [comment]
@thadk added the urx of the transcriber

**Comment by MasSamH** [comment]
@MarianneAnthonette @thadk 
- [ ] Need to determine best place for tracking progress of transcriptions complete
- [ ] Need url from each of the Otterai transcribe interview and pull that into the primary sheet [Brigade Contact Sheet]
- [ ] Create new location for spreadsheet tracking progress 

Separate points Marianne is investigating:
- [ ] How are we capturing processes outside of what are documented
- [ ] Marianne starting on outline for research plan.

**Comment by MarianneAnthonette** [comment]
Additional fields to add to transcription template:
- [ ] Length of interview
- [ ] Otter.ai link
- [ ] Transcription status

**Comment by MarianneAnthonette** [comment]
@MasSamH Typed a rough outline of the [research analysis plan](https://docs.google.com/document/d/10Z90J2TPnoVy3cG96zawP4rw1eeyrdlahPYgHkbn3Pg/edit#). Definitely not set in stone, nor fleshed out, but can possibly inform future issues to make.

**Comment by MasSamH** [comment]
@MarianneAnthonette @jkropko @raquelnish 
- Review and straw man of Research Analysis plan by Raquel and Jonathan
- Create issues matching elements in the Research Analysis plan and add to OKR document - with Sam
- Marianne reaching out to Research Analysts volunteers - capturing volunteers in UXR availability form and add columns to capture which areas they are interested in.
- Determining how we want to code the qual data - consult with Thad

Resource:
[research analysis plan](https://docs.google.com/document/d/10Z90J2TPnoVy3cG96zawP4rw1eeyrdlahPYgHkbn3Pg/edit#l)

**Comment by MarianneAnthonette** [comment]
@MasSamH Made more progress to the Research Analysis Plan. The text in bold can be made into issues (with the other bullet points made into action items). Probably skip making issues for the 'Analysis' section for now.

Good idea to set up a discussion with @thadk, @jkropko, and @raquelnish  (and other research analysis volunteers with experience) next week about **fleshing out the research analysis protocol** (what we want to get out of the research data).

**Comment by MasSamH** [comment]
@MarianneAnthonette 
Discussion to be scheduled after 25th Nov. to Jon, Thad, Raquel to complete, plus to other volunteers.

**Comment by MasSamH** [comment]
@MasSamH Create issues matching elements in the Research Analysis plan and add to OKR document - with Sam

**Comment by MarianneAnthonette** [comment]
Sam will work on this and provide an update on Saturday's meeting.

**Comment by MasSamH** [comment]
@Baleja We will cover the Research Analysis plan related issues as part of the OKR/WBS audit that Serena is leading.

**Comment by Baleja** [comment]
@MarianneAnthonette Next step is for Bonnie, Serena & Mari to meet and go through [this board](https://github.com/codeforamerica/brigade-playbook/projects/2)

**Comment by Baleja** [comment]
Will ask for time after thursday meeting.

**Comment by celeste-hub** [comment]
We plan to meet on Saturday 19/12.

**Comment by MasSamH** [comment]
@MarianneAnthonette 
- One more clean up session between Marianne, Bonnie, Raquel - meeting on 29th Dec. 
- Issues that need focus: 55, 57/59/65
