### ISSUE TITLE
Analysis: Brigades' Highest Priorities

### ISSUE THREAD

**Issue by MarianneAnthonette** [codeforamerica/brigade-playbook#65]
### Overview
We need to understand what Brigades need an example/model for, identify new topics to include in future iterations of the BOP, and identify trends in priorities among: Brigade size, Region, Length of leadership

### Action Items
- [ ] Ranking
   - [ ] Coding/theming qualitative responses
   - [ ] Exploratory data analysis with the quantitative data
- [ ] Additional topics
   - [ ] Create a label/tag for each response
   - [ ] Affinity mapping session (via Miro)
- [ ] Do a cross-analysis of findings from the ranking and additional topics

### Resources/Instructions
[Brigades’ Highest Priorities - Ranking (Main sheet)](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=825325863)
[Brigades’ Highest Priorities - Additional topics (Main sheet)](https://docs.google.com/spreadsheets/d/1EhoVi9VsI7FQw6Th1Q-7KIz1uyWQBowErSKLc9w8oVo/edit#gid=0)

**Comment by MarianneAnthonette** [comment]
**Tasks (12/09 - 12/16)**
- Quantitative analysis discussion (led by Jon): Need to discuss when to hold this discussion
- Ranking: Create initial codes for the qualitative responses (for the interviews you organized).
- Additional topics: Create a label/tag for each response (for the interviews you organized).

**Comment by celeste-hub** [comment]
@MarianneAnthonette Spilt the actions into issues.

**Comment by Baleja** [comment]
From Mari: 
Most of the issue was already taken care of by the Interview Priority Analysis Template.
Other issues related to analyzing the data will be created when there are developments from the next research analysis (qual and quant) meetings (we want to see our preliminary findings from 25% of the interviews).
Action: Probably close this issue.

**Comment by Baleja** [comment]
A new issue will be made for P&P for affinity mapping for multiple interviews.
