### ISSUE TITLE
Issue tracking for WBS & OKRs BOP

### ISSUE THREAD

**Issue by Baleja** [codeforamerica/brigade-playbook#68]
### Overview
This is to keep track of the issues in the WBS and OKR sheet. 

### Action Items

- [ ] Row number on spreadsheet 
- [ ] Description of the task from spreadsheet
- [ ] Issues which seem related and their titles, not already represented on the sheet. 
- [ ] Change colour of cell for review
- [ ] Review comments

### Resources/Instructions
[BOP WBS & OKR](https://docs.google.com/spreadsheets/d/12SHS1MqdrelWjWf2xjZd9gMeQ6JFI2E9sZ2B3ODZ1bU/edit#gid=30376616)

**Comment by celeste-hub** [comment]
@Baleja continues to audit issues.

**Comment by MasSamH** [comment]
@Baleja new issues being added and targeting 29th Dec. 
- coordinate all new UXR issues from Marianne

**Comment by Baleja** [comment]
Added issues are highlighted in yellow in the WBS.

**Comment by Baleja** [comment]
Review closed issues that were similar. #59

**Comment by Baleja** [comment]
Progress: Need to review the new issues made with the OKRs
Blockers: Time
Availability: 6 hours this week till next thurs
ETA: next thurs.

**Comment by Baleja** [comment]
Issues to add to OKRS:
Training: #47 #41 #32
Affinity Mapping: #129 & #153, #65
Quantitate analysis: #140 -#147
Transcription Process: #56 #57 #59 #71 #74 #49 
Analysis process: #58 #62
Deliverables: #54

**Comment by Baleja** [comment]
Sync the issue audits with the NAC updates to present to bonnie 22nd Feb
